<?php

return [
    'title' => 'Elite Repasse Admin v2',
    'subtitle' => 'Painel moderno e responsivo (migração sem Filament)',

    'modules' => [
        'dashboard' => [
            'label' => 'Dashboard',
            'description' => 'Visão executiva em tempo real',
            'icon' => 'grid',
            'legacy_path' => '/admin/dashboard',
            'status' => 'novo',
            'show_in_quick_access' => true,
            'v2_path' => '/painel-admin',
            'actions' => ['visualizar'],
        ],
        'clients' => [
            'label' => 'Clientes',
            'description' => 'Gestão de cadastro, aprovação e bloqueio',
            'icon' => 'users',
            'legacy_path' => '/admin/clients',
            'status' => 'novo',
            'show_in_quick_access' => true,
            'v2_path' => '/painel-admin/clientes',
            'actions' => ['listar', 'criar', 'editar', 'aprovar', 'bloquear'],
        ],
        'vehicles' => [
            'label' => 'Veículos',
            'description' => 'Estoque, disponibilidade e mídia',
            'icon' => 'car',
            'legacy_path' => '/admin/vehicles',
            'status' => 'novo',
            'show_in_quick_access' => true,
            'v2_path' => '/painel-admin/veiculos',
            'actions' => ['listar', 'criar', 'editar', 'anexar-imagens', 'alterar-status'],
        ],
        'orders' => [
            'label' => 'Pedidos',
            'description' => 'Fluxo operacional da venda',
            'icon' => 'shopping-bag',
            'legacy_path' => '/admin/orders',
            'status' => 'novo',
            'show_in_quick_access' => true,
            'v2_path' => '/painel-admin/pedidos',
            'actions' => ['listar', 'visualizar', 'confirmar', 'gerar-contrato', 'gerar-fatura', 'confirmar-pagamento', 'cancelar'],
        ],
        'contracts' => [
            'label' => 'Contratos',
            'description' => 'Assinaturas, envio e rastreio',
            'icon' => 'file-signature',
            'legacy_path' => '/admin/contracts',
            'status' => 'novo',
            'show_in_quick_access' => true,
            'v2_path' => '/painel-admin/contratos',
            'actions' => ['listar', 'visualizar', 'enviar-whatsapp', 'copiar-link', 'acompanhar-assinatura'],
        ],
        'documents' => [
            'label' => 'Documentos',
            'description' => 'Anexos, validação e download',
            'icon' => 'paperclip',
            'legacy_path' => '/admin/documents',
            'status' => 'novo',
            'show_in_quick_access' => true,
            'v2_path' => '/painel-admin/documentos',
            'actions' => ['listar', 'criar', 'editar', 'anexar', 'verificar', 'rejeitar', 'download'],
        ],
        'tickets' => [
            'label' => 'Tickets',
            'description' => 'Atendimento e resposta ao cliente',
            'icon' => 'message-circle',
            'legacy_path' => '/admin/tickets',
            'status' => 'novo',
            'show_in_quick_access' => false,
            'v2_path' => '/painel-admin/tickets',
            'actions' => ['listar', 'criar', 'editar', 'responder', 'atribuir'],
        ],
        'financeiro' => [
            'label' => 'Gestão Financeira',
            'description' => 'Cobranças e conciliação operacional',
            'icon' => 'wallet',
            'legacy_path' => '/admin/gestao-financeira',
            'status' => 'novo',
            'show_in_quick_access' => true,
            'v2_path' => '/painel-admin/financeiro',
            'actions' => ['visualizar', 'filtrar', 'baixar', 'acompanhar-cobranca', 'confirmar-pagamento'],
        ],
        'relatorios' => [
            'label' => 'Relatórios',
            'description' => 'Indicadores e exportações',
            'icon' => 'chart',
            'legacy_path' => '/admin/relatorios',
            'status' => 'novo',
            'show_in_quick_access' => true,
            'v2_path' => '/painel-admin/relatorios',
            'actions' => ['visualizar', 'exportar-csv', 'exportar-pdf', 'acompanhar-metricas'],
        ],
        'whatsapp-instancias' => [
            'label' => 'WhatsApp Instâncias',
            'description' => 'Conectividade e diagnóstico Evolution',
            'icon' => 'plug',
            'legacy_path' => '/admin/whatsapp-instancias',
            'status' => 'novo',
            'show_in_quick_access' => false,
            'v2_path' => '/painel-admin/whatsapp-instancias',
            'actions' => ['listar', 'criar', 'editar', 'conectar', 'qrcode', 'teste-envio'],
        ],
        'whatsapp-inbox' => [
            'label' => 'WhatsApp Inbox',
            'description' => 'Gestão central de mensagens',
            'icon' => 'inbox',
            'legacy_path' => '/admin/whatsapp-inbox',
            'status' => 'novo',
            'show_in_quick_access' => false,
            'v2_path' => '/painel-admin/whatsapp-inbox',
            'actions' => ['visualizar', 'responder'],
        ],
        'email-templates' => [
            'label' => 'Templates de E-mail',
            'description' => 'Modelos e automações transacionais',
            'icon' => 'mail',
            'legacy_path' => '/admin/email-templates',
            'status' => 'novo',
            'show_in_quick_access' => true,
            'v2_path' => '/painel-admin/email-templates',
            'actions' => ['listar', 'criar', 'editar', 'gerar-com-ia', 'previsualizar'],
        ],
        'landing-settings' => [
            'label' => 'Configurações da Landing',
            'description' => 'Conteúdo institucional e comercial',
            'icon' => 'settings',
            'legacy_path' => '/admin/landing-settings',
            'status' => 'novo',
            'show_in_quick_access' => false,
            'v2_path' => '/painel-admin/landing-settings',
            'actions' => ['listar', 'criar', 'editar'],
        ],
        'about-page-settings' => [
            'label' => 'Página Sobre Nós',
            'description' => 'Fotos, equipe, depoimentos e vídeos',
            'icon' => 'info',
            'legacy_path' => '/admin/about-page-settings',
            'status' => 'novo',
            'show_in_quick_access' => false,
            'v2_path' => '/painel-admin/about-page-settings',
            'actions' => ['editar'],
        ],
        'landing-banners' => [
            'label' => 'Banners da Landing',
            'description' => 'Imagens do carrossel principal',
            'icon' => 'image',
            'legacy_path' => '/admin/landing-banners',
            'status' => 'novo',
            'show_in_quick_access' => false,
            'v2_path' => '/painel-admin/landing-banners',
            'actions' => ['listar', 'criar', 'editar', 'excluir', 'reordenar'],
        ],
        'configuracoes-gerais' => [
            'label' => 'Configurações Gerais',
            'description' => 'SMTP, reCAPTCHA, Google e Gemini',
            'icon' => 'sliders',
            'legacy_path' => '/admin/configuracoes-gerais',
            'status' => 'novo',
            'show_in_quick_access' => false,
            'v2_path' => '/painel-admin/configuracoes-gerais',
            'actions' => ['visualizar', 'editar', 'testar-email'],
        ],
        'general-documents' => [
            'label' => 'Documentos Gerais',
            'description' => 'Documentos internos para download no portal',
            'icon' => 'file-text',
            'legacy_path' => '/admin/general-documents',
            'status' => 'novo',
            'show_in_quick_access' => false,
            'v2_path' => '/painel-admin/documentos-gerais',
            'actions' => ['listar', 'criar', 'editar', 'excluir'],
        ],
        'vehicle-reports' => [
            'label' => 'Laudos e Vistorias',
            'description' => 'Checklist técnico de veículos com aprovação',
            'icon' => 'clipboard-check',
            'legacy_path' => '/admin/vehicle-reports',
            'status' => 'novo',
            'show_in_quick_access' => false,
            'v2_path' => '/painel-admin/laudos',
            'actions' => ['listar', 'criar', 'visualizar', 'aprovar', 'reprovar'],
        ],
        'notificacoes' => [
            'label' => 'Central de Notificações',
            'description' => 'Histórico, envio manual e broadcast',
            'icon' => 'bell',
            'legacy_path' => '/admin/central-notificacoes',
            'status' => 'novo',
            'show_in_quick_access' => false,
            'v2_path' => '/painel-admin/notificacoes-admin',
            'actions' => ['listar', 'enviar-manual', 'enviar-broadcast', 'marcar-lidas'],
        ],
    ],
];
